name: dswx_s1
channels:
 - conda-forge
dependencies:
 - python<3.12
 - asf_search>=6.7.0
 - boto3
 - click
 - contextily
 - dateparser
 - dem_stitcher>=2.5.4
 - fiona
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - gdal<3.8
 - geopandas
 - h5py
 - hyp3_sdk
 - ipykernel
 - jinja2
 - jupyter
 - jupyterlab
 - jupytext
 - matplotlib
 - mgrs
 - nbdime
 - notebook
 - numpy
 - opencv
 - papermill
 - pip
 - planet
 - pydantic
 - pytest
 - python-dotenv
 - pyyaml
 - rasterio
 - ruamel.yaml
 - requests
 - scikit-image
 - scikit-learn
 - shapely
 - tqdm
 - yamale
 - pip:
   - elasticsearch==7.13.4 # https://github.com/nasa/opera-sds-pcm/blob/develop/setup.py#L74
   - elasticsearch-dsl<8.0 # To ensure version 7 is compatible: https://elasticsearch-dsl.readthedocs.io/en/latest/#compatibility
   - pysheds
   - git+https://github.com/OPERA-Cal-Val/tile-stitcher
   - git+git@github.com:cmarshak/DSWX-SAR.git@default-params-update
